package net.kyau.afterhours;

import javax.annotation.Nonnull;

import net.kyau.afterhours.config.AfterHoursTab;
import net.kyau.afterhours.config.ConfigHandler;
import net.kyau.afterhours.dimension.DimensionHandler;
import net.kyau.afterhours.dimension.WorldGenerator;
import net.kyau.afterhours.event.GuiHandler;
import net.kyau.afterhours.init.ModBlocks;
import net.kyau.afterhours.init.ModEnchants;
import net.kyau.afterhours.init.ModItems;
import net.kyau.afterhours.init.ModRecipes;
import net.kyau.afterhours.init.ModVanilla;
import net.kyau.afterhours.init.RecipeRepair;
import net.kyau.afterhours.network.PacketHandler;
import net.kyau.afterhours.proxy.IProxy;
import net.kyau.afterhours.references.ModInfo;
import net.kyau.afterhours.references.Ref;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.item.Item.ToolMaterial;
import net.minecraft.item.ItemArmor.ArmorMaterial;
import net.minecraftforge.common.util.EnumHelper;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.network.NetworkRegistry;
import net.minecraftforge.fml.common.registry.GameRegistry;
import net.minecraftforge.oredict.RecipeSorter;
import net.minecraftforge.oredict.RecipeSorter.Category;

@Mod(modid = ModInfo.MOD_ID,
     name = ModInfo.MOD_NAME,
     version = ModInfo.MOD_VERSION,
     guiFactory = ModInfo.GUI_FACTORY,
     acceptedMinecraftVersions = "[1.8.9]",
     dependencies = "required-after:Forge@[11.15.1.1722,);")
public class AfterHours {

  @Mod.Instance(ModInfo.MOD_ID)
  public static AfterHours instance;

  @SidedProxy(clientSide = ModInfo.PROXY_CLIENT,
              serverSide = ModInfo.PROXY_SERVER)
  public static IProxy proxy;

  public static CreativeTabs AfterHoursTab = new AfterHoursTab(CreativeTabs.getNextID(), "AfterHours");

  public static ToolMaterial darkmatter;
  public static ArmorMaterial darkmatterArmor;

  public static int guiIndex = 0;
  public static final int GUI_VOIDJOURNAL = guiIndex++;
  public static final int GUI_QRD = guiIndex++;
  public static final int GUI_QS = guiIndex++;

  @Mod.EventHandler
  public void preInit(@Nonnull FMLPreInitializationEvent event) {
    // hard-coded mcmod.info
    event.getModMetadata().autogenerated = false;
    event.getModMetadata().authorList.add(ModInfo.MOD_AUTHOR);
    event.getModMetadata().description = ModInfo.MOD_DESC;
    event.getModMetadata().url = ModInfo.MOD_URL;
    event.getModMetadata().logoFile = ModInfo.MOD_LOGO;
    ConfigHandler.init(event.getSuggestedConfigurationFile());
    DimensionHandler.init();
    GameRegistry.registerWorldGenerator(new WorldGenerator(), 1);
    PacketHandler.init();
    RecipeSorter.register(ModInfo.MOD_ID + ":repair", RecipeRepair.class, Category.SHAPELESS, "after:minecraft:shapeless");
    darkmatter = EnumHelper.addToolMaterial("DARKMATTER", Ref.DarkMatter.HARVEST_LEVEL, Ref.DarkMatter.DURABILITY, Ref.DarkMatter.EFFICIENCY, Ref.DarkMatter.DAMAGE, 100);
    darkmatterArmor = EnumHelper.addArmorMaterial("DARKMATTER", ModInfo.MOD_ID + ":" + "darkmatter", 100, new int[] {
        3,
        8,
        6,
        3 }, 30);
    proxy.registerEventHandlers();
    proxy.registerKeybindings();
    ModEnchants.registerEnchants();
    ModItems.registerItems();
    ModBlocks.registerBlocks();
    ModVanilla.registerItems();
    proxy.initRenderingAndTextures();
  }

  @Mod.EventHandler
  public void init(@Nonnull FMLInitializationEvent event) {
    ModRecipes.init();
    NetworkRegistry.INSTANCE.registerGuiHandler(this, new GuiHandler());
  }

  @Mod.EventHandler
  public void postInit(@Nonnull FMLPostInitializationEvent event) {
    ModRecipes.post();
    proxy.registerClientEventHandlers();
  }
}
